### DISCUSSION TITLE
Recorded videos in Lovelace?

### DISCUSSION THREAD

**Discussion by INPoppoRTUNE** [JurajNyiri/HomeAssistant-Tapo-Control#642] [Q&A] [answered]
# Issues
I'd like to use [gallery card](https://github.com/lukelalo/gallery-card) to display a gallery of recorded videos in Lovelace, but I cannot find a way to make it works.
As far as I'm understanding:
- cold storage path is setted to `/config/www/tapo_control` and it is [automatically emptied](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/418#issuecomment-1756474825) even if I setted the number of hours to keep synchronized to 1h;
-  gallery card [accept URI scheme only](https://github.com/lukelalo/gallery-card#configuration-variables), no local path;
# Attempt instructions
- I mounted `/config/www/tapo_control` in `configuration.yaml`
```yaml
homeassistant:
    media_dirs:
        tapo: /config/www/tapo_control
```
- I passed the URI scheme to the gallery card
```yaml
type: custom:gallery-card
entities:
  - path: media-source://media_source/tapo
    recursive: true
show_controls: true
include_images: false
include_video: true
autoplay: true
interval: 5000
```
# Results
The folder is automatically emptied, so I'm unable to see any video listed in the gallery card integration unless I recently played one from the media sources or it's being synchronized.
## Expected results
Having a folder with 1h of videos synced, accessible from the gallery card integration.

I'm sure I'm missing something super obvious, but I'm bashing my head in circle without reaching any solution.
Any suggestions? Thanks for your time.

**Comment by JurajNyiri** [comment, marked as answer]
This works like this on purpose because of privacy reasons. **Hot storage** /config/www/tapo_control will be always emptied out after 1 hour and has further obfuscation in place to prevent anyone guessing the file name and path. 
What you can do is set cold storage to something else, like /config/www/tapo_control_cold_storage and then it will stay but **_your recordings will be accessible WITHOUT authorization to everyone who can access your HA host_**, provided they know the path to the cold storage "/config/www/tapo_control_cold_storage" so I recommend setting it to a random folder string name **_at least_**.

**Reply by JurajNyiri** [reply]
@INPoppoRTUNE Updated^ see editted message please.

**Reply by INPoppoRTUNE** [reply]
So my updated setup is:
# Cold storage folder
Created a new folder `/config/www/custom_rng_generated_long_path_for_cold_storage`
# configuration.yaml
```yaml
homeassistant:
   media_dirs:
    tapo: /config/www/custom_rng_generated_long_path_for_cold_storage
```
# Tapo media synchronization settings
- Enable media synchronization: checked
- Number of hours to keep synchronized: 1
- Cold storage path: /config/www/custom_rng_generated_long_path_for_cold_storage
# Gallery card
```yaml
type: custom:gallery-card
entities:
  - path: media-source://media_source/tapo
    recursive: true
show_controls: true
include_images: false
include_video: true
autoplay: true
interval: 5000
```
---
At the moment the `/config/www/custom_rng_generated_long_path_for_cold_storage` folder is empty and the `sensor.camera_recordings_synchronization` entity goes from `starting` to `idle` after restarting Home Assistant.
I guess it need some time to fully sync all 1h of videos and will do it sometime today autonomously(?)
Will check on the status in a couple of hours. Please let me know if any of my setting are not setted correctly. Thanks for your time!

Edit: I just realized I misinterpreted this instruction: "You need to also define the number of hours to synchronize". This parameter define the datetime difference between now() and the video date, not the total number of hours of video to synchronize. I now updated the Number of hours to keep synchronized to 168 (aka 1 week) and the synchronization started immediately upon restart.
**I'd also like to ask if it's possible to implement a filename format field in settings**: gallery card expect a `file_name_format` in datetime format (ES: `file_name_format: YYYY_MM_DD__HH_mm_ss`), so I don't think it's compatible with the Unix format used by this integration.

**Reply by jojeji** [reply]
You can use "file_name_date_begins" and file_name_format=X to solve it
Filename look like "1734829030-1734829094.mp4", so I start at char 12 parsing the date.

```
type: custom:gallery-card
entities:
  - path: media-source://media_source/tapo/xyz
    recursive: true
  - path: media-source://media_source/tapo/zxy
    recursive: true
  - path: media-source://media_source/tapo/yzx
    recursive: true
maximum_files: 5
file_name_format: X
file_name_date_begins: "12"
caption_format: DD.MM.YY hh:mm
menu_alignment: bottom
```

**Reply by INPoppoRTUNE** [reply]
@jojeji my dude out of nowere!
Worked flawlessly, thanks!

**Reply by ronttidev** [reply]
Sorry for necromancing this thread but I have similar issues where I cannot get the recordings to show up in the gallery card and I am unsure what I am doing wrong. My yaml looks like this at the moment but I get "Failed to browse and found no media files" error message:

```
type: custom:gallery-card
entities:
  - path: media-source:///config/www/randomstringgenerated/videos
    recursive: true
maximum_files: 5
file_name_format: YY-MM-DD_HH-mm-ss_BST
menu_alignment: bottom
```

I made a python script that changes the format from UNIX time to BST so the videos in /config/www/randomstringgenerated/videos are in named like "2025-07-22_09-19-21_BST". I did this because I thought Jojeji's suggestion just was not working for me so I tried this instead, but no luck still.

configuration.yaml looks like this

homeassistant:
   media_dirs:
    tapo:  /config/www/randomstringgenerated/

Any ideas what am I missing?

**Reply by jojeji** [reply]
just checked my configuration and it looks like this:
```
homeassistant:
  media_dirs:
    tapo: /config/www/tapo_control/

```
and this is my dashboard config:
```
type: custom:gallery-card
entities:
  - path: media-source://media_source/tapo/garten3/videos
    recursive: true
  - path: media-source://media_source/tapo/garten/videos
    recursive: true
  - path: media-source://media_source/tapo/terasse/videos
    recursive: true
maximum_files: 8
file_name_format: X
file_name_date_begins: "12"
caption_format: DD.MM.YY hh:mm
menu_alignment: bottom
video_muted: true
parsed_date_sort: DD.MM.YY hh:mm
```

So I think you have to insert this path in your dashboard: "media-source://media_source/tapo/videos"
