### ISSUE TITLE
Bug: Motion Detection Mode cant be changed

### ISSUE THREAD

**Issue by MasterTim17** [JurajNyiri/HomeAssistant-Tapo-Control#137]
**Describe the bug**
Template switch cant change motion_detection_mode. Also doesnt work with calling the service via developer settings.

**Expected behavior**
motion_detection_mode can be changed to off/low/normal/high

**Log**
2022-01-23 17:40:27 INFO (MainThread) [homeassistant.helpers.script.motion_detection_mode] Motion Detection mode: Running template script
2022-01-23 17:40:27 INFO (MainThread) [homeassistant.helpers.script.motion_detection_mode] Motion Detection mode: Executing step call service

```
switch:
  - platform: template
    switches:
      tapo_motion_detection:
        friendly_name: Motion Detection mode
        value_template: "{{ state_attr('camera.tapo_camera_hd', 'motion_detection_sensitivity') != 'off' }}"
        turn_on:
          service: tapo_control.set_motion_detection_mode
          data:
            entity_id: "camera.tapo_camera_hd"
            motion_detection_mode: "high"
        turn_off:
          service: tapo_control.set_motion_detection_mode
          data:
            entity_id: "camera.tapo_camera_hd"
            motion_detection_mode: "off"
        icon_template: >-
          {% if state_attr('camera.tapo_camera_hd', 'motion_detection_sensitivity') != 'off' %}
            mdi:motion-sensor
          {% else %}
            mdi:motion-sensor-off
          {% endif %}
```

**Camera (please complete the following information):**
 - Device Model: [C210]

**Using stream component**
[yes]

**Camera has all attributes filled out properly in developer tools**
yes (the state of motion detection is called motion_detection_sensitivity)

**HASS Environment**
[Raspberry with hass os]

**Comment by JurajNyiri** [comment]
Service does work, just tested with my C210.

```
service: tapo_control.set_motion_detection_mode
data:
  motion_detection_mode: high
target:
  entity_id: camera.bedroom_sd
```

FW: 1.1.8 Build 210425 Rel.66776n(4555)
