### ISSUE TITLE
Turn off privacy mode doesn't work

### ISSUE THREAD

**Issue by rikman122** [JurajNyiri/HomeAssistant-Tapo-Control#2]
Hi! Nice job here!

I'm testing the integration and find out that turning off privacy mode isn't working. I can turn it on but not off. This is the service call:
**tapo_control.set_privacy_mode**
  entity_id: tapo_control.cam
  privacy_mode: 'off'

I'm in the latest HA core and v1.0 tapo control integration.

**Comment by JurajNyiri** [comment]
Hello, which camera do you have?

**Comment by rikman122** [comment]
Hi,

I have Tapo C200 camera. No errors in logs and turning the privacy mode on with the same service works.

**Comment by JurajNyiri** [comment]
Please try following:

- Update to 1.2
- If it still doesn't work, try running with following script, that one is 100% working on my Tapo C200. Just replace the entity_id and script id and name if you want to

```
set_bedroom_camera_away:
  alias: Set Bedroom Camera Away
  sequence:
  - data:
      privacy_mode: 'off'
    service: tapo_control.set_privacy_mode
    entity_id: tapo_control.bedroom
```

Triple check the entity_id is correct.

And always check logs and paste here if there is something there... if the script works, please screenshot how you were calling it before.
