### ISSUE TITLE
"Stream integration is not set up." when recording stream

### ISSUE THREAD

**Issue by fballiano** [JurajNyiri/HomeAssistant-Tapo-Control#253]
### Description

Hi,
I gotta say I'm pretty new to this world but I couldn't find any documentation on this problem I'm facing.

I'm creating an automation that records a video when the motion sensor on my tapo c110 triggers. The problem is that when the automation is triggered (or if I call the service manually) I get this "Stream integration is not set up." error.

The configuration is:
```
id: '1668599422942'
alias: Registra video con movimento
description: ''
trigger:
  - type: motion
    platform: device
    device_id: aa936389760853989280d0a5d02c08e6
    entity_id: binary_sensor.camera_cucina_motion
    domain: binary_sensor
condition: []
action:
  - service: camera.record
    data:
      duration: 120
      filename: /tmp/cucina_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4
    target:
      entity_id: camera.camera_cucina_hd_stream
mode: single
```

The stream is working fine (although with delay) from the HA dashboard.

Thanks for any help!

### Reproduction Steps

1. setup camera
2. setup a motion triggered automation and call the "Record Camera" service
3. trigger the motion
4. check the automation trace for the error

### Expected behavior

video gets recorded

### Device Firmware

1.1.21

### Using stream component

Yes

### Does camera work via official integrations?

N/A

### Camera has all attributes filled out in developer tools

No

### HASS Environment

DietPI

### Search for similar issues

Yes
