### ISSUE TITLE
Feature Request: Add switches to device (Privacy Mode, Auto Track Mode, ...)

### ISSUE THREAD

**Issue by david-kalbermatten** [JurajNyiri/HomeAssistant-Tapo-Control#47]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more of a "nice-to-have".

**Describe the solution you'd like**
I would like to have switches added to the device of a camera to toggle stuff like `Privacy Mode`, `Auto Tracking Mode`. Also the motion sensor is not listed in the device of the camera... (see picture below)

**Describe alternatives you've considered**
So far I've been using template switches since I can read the corresponding attributes from the camera entity...
```yaml
# Switches.yaml

- platform: template
  switches:
    tapo_cam_1_privacy_switch:
      friendly_name: Privacy Mode
      value_template: "{{ state_attr('camera.tapo_camera_5489_hd', 'privacy_mode') == 'on' }}"
      turn_on:
        - service: tapo_control.set_privacy_mode
          data:
            entity_id: camera.tapo_camera_5489_hd
            privacy_mode: 'on'
      turn_off:
        - service: tapo_control.set_privacy_mode
          data:
            entity_id: camera.tapo_camera_5489_hd
            privacy_mode: 'off'
      icon_template: >-
        {% if state_attr('camera.tapo_camera_5489_hd', 'privacy_mode') == 'on' %}
          mdi:eye-off-outline
        {% else %}
          mdi:eye-outline
        {% endif %}

    tapo_cam_1_auto_track_switch:
      friendly_name: Auto Track
      value_template: "{{ state_attr('camera.tapo_camera_5489_hd', 'auto_track') == 'on' }}"
      turn_on:
        - service: tapo_control.set_auto_track_mode
          data:
            entity_id: camera.tapo_camera_5489_hd
            auto_track_mode: 'on'
      turn_off:
        - service: tapo_control.set_auto_track_mode
          data:
            entity_id: camera.tapo_camera_5489_hd
            auto_track_mode: 'off'
      icon_template: "mdi:radar"

    tapo_cam_1_alarm_switch:
      friendly_name: Alarm
      value_template: "{{ state_attr('camera.tapo_camera_5489_hd', 'alarm') == 'on' }}"
      turn_on:
        - service: tapo_control.set_alarm_mode
          data:
            entity_id: camera.tapo_camera_5489_hd
            alarm_mode: 'on'
      turn_off:
        - service: tapo_control.set_alarm_mode
          data:
            entity_id: camera.tapo_camera_5489_hd
            alarm_mode: 'off'
      icon_template: >-
        {% if state_attr('camera.tapo_camera_5489_hd', 'alarm') == 'on' %}
          mdi:alarm-note
        {% else %}
          mdi:alarm-note-off
        {% endif %}
```

**Additional context**
_Screenshot of Device missing the `motion_sensor`_
The motions sensor is there, just not listed under the device :D
![image](https://user-images.githubusercontent.com/45201085/101266048-f0629700-374b-11eb-838b-6a8f31943ccc.png)

_Screenshot of template switches in lovelace dashboard_
![image](https://user-images.githubusercontent.com/45201085/101266117-57804b80-374c-11eb-9e89-6deba2415a70.png)
