### ISSUE TITLE
Cameras not discovered

### ISSUE THREAD

**Issue by jterrace** [JurajNyiri/HomeAssistant-Tapo-Control#790]
### Description

My C720 and C325WB cameras are not discovered by the dhcp discovery integration. I think it's because they are not listed in the manifest.json. 

### Reproduction Steps

1. Have a camera not in manifest.json

### Expected behavior

Camera is discovered

### Device Firmware

1.2.2

### Integration Version

6.0.1

### Using stream component

No

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Beelink EQ13

### Search for similar issues

Yes

### Additional information

How did you come up with the large list of models and mac addresses you added to manifest.json? Is there a way to keep it up to date?

Separately, I'm wondering if there might be a better way to do discovery. I found https://github.com/andreikop/python-ws-discovery which does seem to work to find all my tapo cameras, but I can't seem to figure out a way to identify *just* Tapo cameras. You can identify them by model though, here's my scope list when using wsdiscover:

```
Discovered:

 address: 192.168.56.109:2020
  - onvif://www.onvif.org/name/C720
  - onvif://www.onvif.org/hardware/C720
  - onvif://www.onvif.org/Profile/Streaming
  - onvif://www.onvif.org/location/Hong Kong
  - onvif://www.onvif.org/type/NetworkVideoTransmitter

 address: 192.168.56.63:2020
  - onvif://www.onvif.org/name/C720
  - onvif://www.onvif.org/hardware/C720
  - onvif://www.onvif.org/Profile/Streaming
  - onvif://www.onvif.org/location/Hong Kong
  - onvif://www.onvif.org/type/NetworkVideoTransmitter

 address: 192.168.56.171:2020
  - onvif://www.onvif.org/name/C720
  - onvif://www.onvif.org/hardware/C720
  - onvif://www.onvif.org/Profile/Streaming
  - onvif://www.onvif.org/location/Hong Kong
  - onvif://www.onvif.org/type/NetworkVideoTransmitter

 address: 192.168.56.127:2020
  - onvif://www.onvif.org/name/C325WB
  - onvif://www.onvif.org/hardware/C325WB
  - onvif://www.onvif.org/Profile/Streaming
  - onvif://www.onvif.org/location/Hong Kong
  - onvif://www.onvif.org/type/NetworkVideoTransmitter
 ```
