### ISSUE TITLE
Feature Request: expose 2-way audio camera as media_player entity to be able to send TTS

### ISSUE THREAD

**Issue by shlomicthailand** [JurajNyiri/HomeAssistant-Tapo-Control#950]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to send Text-To-Speech audio to my cameras which support 2-way audio.
by the go2rtc documentation - this is possible for Tapo cameras
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-tapo

**Describe alternatives you've considered**
There are many guides on the internet part of them on the go2rtc github how to define this , but all talk about go2rtc as addon, now that its native in HA its imposible to find configuration file go2rtc.yaml and most of the other streams definition do not work.
it will be very nice if the configuration had a radio button if to expose the 2-way cameras as media player , then TTS could be played on the camera itself.

**Additional context**
the guides in the internet talk about defining this - but in 2025 its not possible in configuration.yaml (cause go2rtc is embedded)
```
streams:
  # cloud password without username
  camera1: tapo://cloud-password@192.168.1.123
  # admin username and UPPERCASE MD5 cloud-password hash
  camera2: tapo://admin:UPPERCASE-MD5@192.168.1.123
  # admin username and UPPERCASE SHA256 cloud-password hash
  camera3: tapo://admin:UPPERCASE-SHA256@192.168.1.123
```
and 
```
media_player:
  - platform: webrtc
    name: Dahua Camera
    stream: dahua
    audio: pcmu/48000
  - platform: webrtc
    name: Tapo Camera
    stream: tapo
    audio: pcma
```
