### ISSUE TITLE
Feature Request:Expose cameras as media player entity , be able to send TTS

### ISSUE THREAD

**Issue by shlomicthailand** [JurajNyiri/HomeAssistant-Tapo-Control#951]
**Is your feature request related to a problem? Please describe.**
I want to send Text-To-Speech audio to my cameras which support 2-way audio.

**Describe the solution you'd like**
I want to send Text-To-Speech audio to my cameras which support 2-way audio.
by the go2rtc documentation - this is possible for Tapo cameras
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-tapo

**Describe alternatives you've considere**d
There are many guides on the internet part of them on the go2rtc github how to define this , but all talk about go2rtc as addon, now that its native in HA its imposible to find configuration file go2rtc.yaml and most of the other streams definition do not work.
it will be very nice if the configuration had a radio button if to expose the 2-way cameras as media player , then TTS could be played on the camera itself.

**Additional context**
the guides in the internet talk about defining this - but in 2025 its not possible in configuration.yaml (cause go2rtc is embedded)

```
streams:
  # cloud password without username
  camera1: tapo://cloud-password@192.168.1.123
  # admin username and UPPERCASE MD5 cloud-password hash
  camera2: tapo://admin:UPPERCASE-MD5@192.168.1.123
  # admin username and UPPERCASE SHA256 cloud-password hash
  camera3: tapo://admin:UPPERCASE-SHA256@192.168.1.123
```
and
```
media_player:
  - platform: webrtc
    name: Dahua Camera
    stream: dahua
    audio: pcmu/48000
  - platform: webrtc
    name: Tapo Camera
    stream: tapo
    audio: pcma
```

**Comment by JurajNyiri** [comment]
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/99

It is possible to configure go2rtc following their docs.

**Comment by shlomicthailand** [comment]
@JurajNyiri believe me i have read every post on the subject (most are old from before go2rtc was natively in HA) , and i use chat GPT a lot (which is also out of date) , and there is no simple guide how to do this .

some people got it working - but it was when go2rtc was an add-on , others use shell_commands.

closing this one , and just saying "Its possible , go read the documentation" is not polite or kind.
people who open issues sometimes DO read a lot before asking anything.

**Comment by JurajNyiri** [comment]
1. Install and enable https://github.com/AlexxIT/WebRTC/
2. Modify yaml file go2rtc to add the camera as per the docs

**Comment by shlomicthailand** [comment]
@JurajNyiri - thanks for that , it wasn't clear if i even need WebRTC (cause i don't use it for streaming to browser)
now i have it without any errors in logs but still the camera does not play (not through the test page of go2rtc or the developer actions)


1. go2rtc - built into HA (not in use)
2. go2rtc - which comes after installing WebRTC , this also create the go2rtc.yaml which HA does not expose to us.

the camera stream is created through the UI at http://homeassistant.local:1984/add.html
the go2rtc.yaml looks like this 
```
api:
  password: pass
  username: shlomicthailand
rtsp:
  listen: 127.0.0.1:8554
  password: pass
  username: shlomicthailand
streams:
  bed_cam: tapo://cloud-pass@192.168.1.227

```
3. WebRTC media player configured 
configuration.yaml 
```
media_player:
  - platform: webrtc
    entity_id: media_player.bedroom_cam_media
    name: Bedroom Camera Media
    stream: bed_cam
    audio: auto
```

**Comment by shlomicthailand** [comment]
@JurajNyiri - thanks, this is exactly why i though having this in this integration , can save people so much time !!

**Comment by shlomicthailand** [comment]
Ok, got it working - for the sake of others that going to spend so much time as i did here it is 


# ✅ TTS Working on Tapo Camera Speaker (C100/C210) with go2rtc + HACS WebRTC Integration

I was able to get **text-to-speech (TTS) audio playback on my Tapo C100 camera speaker** fully working using the [go2rtc](https://github.com/AlexxIT/go2rtc) backend and the [WebRTC integration from HACS](https://github.com/AlexxIT/webrtc). This **does NOT use the built-in go2rtc integration in HA 2025**, but rather the **custom WebRTC platform for `media_player`**.

---

## 🧱 Requirements

- Home Assistant (tested on 2025.x)
- [Tapo Control integration](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control)
- [WebRTC integration from HACS](https://github.com/AlexxIT/webrtc)
- `go2rtc` must be running (as part of HACS WebRTC) and accessible at `http://homeassistant.local:1984`
- Tapo camera with **2-way audio support** (tested on C100)

---

## ⚙️ Configuration

### 1. `configuration.yaml`

```yaml
media_player:
  - platform: webrtc
    name: Bedroom Camera Media
    stream: bed_cam
    audio: pcma

tts:
  - platform: google_translate
    service_name: google_say
```

### 2. Add camera stream 
1. Open your browser and go to: http://homeassistant.local:1984
2. Click the ⚙️ gear icon to open the stream editor.
3. Click "Add Temporary Stream".
4. Enter your camera stream URL in this format: `tapo://CloudPassword@192.168.1.100`
 The stream will be assigned a name like bed_cam. Use this name in your configuration.yaml under stream:.

⚠️ For Tapo cameras, temporary streams are required due to authentication method.

### 3. To test TTS
1. go to Developer Tools → Actions in Home Assistant.
2. Select the action: `tts.google_say`
3. For the entity, pick your virtual media player, e.g.: `media_player.bedroom_camera_media`
4. In the Message  field, enter: "Hello, this is a test message"
5. Click Execute. Your Tapo camera speaker should play the message.
