### ISSUE TITLE
Feature Request: Two way audio - audio entities.

### ISSUE THREAD

**Issue by CoYoNq** [JurajNyiri/HomeAssistant-Tapo-Control#99]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
use audio in 2way audio enabled devices for rec/playback 

**Additional context**
Would be great to use the audio features in scripts (ie, recieving voice commands or sending custom notifications)

**Comment by JurajNyiri** [comment]
Unfortunately, not currently possible as noone figured out how it works. First someone will need to do that and then it can be implemented into https://github.com/JurajNyiri/pytapo/ .

**Comment by JurajNyiri** [comment]
Need more help at https://github.com/JurajNyiri/pytapo/issues/41

**Comment by dm82m** [comment]
@JurajNyiri as AlexxIT found a way and provides the functionality to use 2-way-audio through go2rtc - is there any plan that your integration will support 2-way-audio in the future?

**Comment by JurajNyiri** [comment]
It is now possible to use camera as media_player, see [webrtc integration readme](https://github.com/AlexxIT/WebRTC#stream-to-camera). This gives you a possibility to send any sound to the camera, or even open 2 way talk session via a browser in any device.

I will keep this opened as I might implement it also here in the future, but it is not a priority right now.

**Comment by krasatos** [comment]
Hey there :)
Any progress on this front?

**Comment by JurajNyiri** [comment]
This can be achieved with webrtc so the priority is very low to not going to implement.

**Comment by ssorgatem** [comment]
It doesn't seem to work with my WS320 cameras with webrtc... it does for the C200 though

**Comment by pepijndevos** [comment]
Could anyone share their working tapo webrtc two way configuration?

**Comment by ssorgatem** [comment]
> Could anyone share their working tapo webrtc two way configuration?

Make sure to use go2rtc with the "tapo://" protocol (not direct rtsp) to connect to the camera. I use the one bundled with frigate.

Then, on configurtation.yaml I have this:

```
media_player:
  - platform: webrtc
    name: tapo_davant
    stream: davant
    audio: pcma
  - platform: webrtc
    name: tapo_barbacoa
    stream: barbacoa
    audio: pcma
  - platform: webrtc
    name: tapo_nens
    stream: nens
    audio: pcma
  - platform: webrtc
    name: tapo_bressol
    stream: bressol
    audio: pcma
```

Where "stream" is the name of the stream in your go2rtc config.

This is working for C200 cameras but not for WS320 cameras for some reason.
